spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url:
      jdbc:h2:mem:testdb
  sql:
    init:
      mode: always

logging:
  level:
    sql: debug
